version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout

      # Install SSH client and sshpass
      - run:
          name: Install SSH client and sshpass
          command: |
            apt-get update && apt-get install -y openssh-client sshpass

      # SSH into the server and run commands with verbose logging
      - run:
          name: Run commands on server
          command: |
            sshpass -p 8p53YschXLQU ssh -v -o "StrictHostKeyChecking=no" -o "HostKeyAlgorithms=ssh-rsa" -p 21098 xwaismji@server66.web-hosting.com "cd ~/public_html && git pull && php artisan migrate --force && php artisan config:clear"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
