version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout

      # Install SSH client
      - run:
          name: Install SSH client
          command: |
            apt-get update && apt-get install -y openssh-client

      # Configure SSH connection
      - add_ssh_keys:
          fingerprints:
            - "15:93:4f:b5:03:d9:61:ee:2f:4d:9c:e8:1f:9c:66:62"

      # SSH into the server and run commands
      - run:
          name: Run commands on server
          command: |
            ssh -o "StrictHostKeyChecking=no" -o "HostKeyAlgorithms=ssh-rsa,ssh-dss" -p 21098 xwaismji@server66.web-hosting.com "cd ~/public_html && git pull && echo 'Hello, SSH!' && php artisan migrate --force && php artisan config:clear"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
